name: MLOps tourism data

on:
  workflow_dispatch:
  
jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/common-setup

      - name: Install dependencies
        run: uv pip install -r tourism_project/requirements.txt

      - name: Upload Dataset to HuggingFace Hub
        env: 
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: uv run tourism_project/model_building/data_register.py
